### ISSUE TITLE
Problème commutativité des opérateurs 

### ISSUE THREAD

**Issue by cecilebraun** [PolytechUPMC-ICP/PolytechUPMC-ICP-Template-alexm7878#1]
@alexm7878 a écrit 

> Bonjour,
> j'ai un petit soucis dans mon code sur les Templates.
> Je peux écrire une opération entre une matrice et un réel  mais pas l'écrire dans l'autre sens.
> M2 = M1 +2 => fonctionne.
> M2 = 2+M1 => ne fonctionne pas.
> 
> Je n'arrive pas à comprendre pourquoi la surcharge d'opérateur ne peut pas s'appliquer dans les deux sens.

**Comment by cecilebraun** [comment]
Que se passe-t-il quand vous appelez ces opérations ?
* M1 +2  est équivalent à M1.operator+(2)
* 2 + M1 est équivalent à 2.operator+(M1)

_L'opérateur + qui prend une matrice n'est pas définit pour les int !_

Ce que vous pouvez faire c'est définir 2 opérateurs en membre ami pour couvrit les 2 cas
friend Matrix operator+(Matrix , U)
friend Matrix operator+U, Matrix)

Pour plus de détails sur poutquoi friend lire les item 24 et 46 de Scott Meyers "effective C++" (3ème édition).

**Comment by alexm7878** [comment]
Merci de votre réponse.
Je comprends mieux pourquoi cela ne marchait pas !
N'ayant pas compris exactement le fonctionnement des "Friend", je vais lire attentivement la référence que vous m'avez donné.
Cordialement,
Alexandre Maury

**Comment by alexm7878** [comment]
Je suis désolée de vous embêtez avec ça encore....
J'ai essayer de faire les fonctions :
friend Matrix<T> operator+(Matrix<T> , U)
friend Matrix<T> operator+(U, Matrix<T>)

Mais le seul moyen pour que cela fonction est de les faire dans  la déclaration de la  fonction directement dans la classe, je n'ai pas trouvé de solution pour  les mettre en dehors comme pour les autres fonctions, je suppose que les mettre dans la classe n'est pas très propre.

**Comment by cecilebraun** [comment]
Vous n'avez pas le choix, il faut que les fonctions soient dans la classe, sinon à l'édition de lien cela ne marchera pas (voir item 46)

**Comment by alexm7878** [comment]
D'accord !  Je n'avais pas très bien compris cette partie. 
Merci pour votre aide.
